# Generated by Django 3.1.5 on 2021-01-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # *NOTES*
        # The `operations` attribute defines the operations to be performed in this migration.
        # In this case, it contains a single `CreateModel` operation.
        # https://docs.djangoproject.com/en/5.0/ref/migrations/#operation-classes

        migrations.CreateModel(
            name='Review',
            # *NOTES*
            # The `name` attribute specifies the name of the model to be created, in this case, 'Review'.
            # https://docs.djangoproject.com/en/5.0/ref/migrations/#createmodel

            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # *NOTES*
                # This line defines the `id` field as an `AutoField`, which is an auto-incrementing primary key field.
                # https://docs.djangoproject.com/en/5.0/ref/models/fields/#autofield

                ('user_name', models.CharField(max_length=100)),
                # *NOTES*
                # This line defines the `user_name` field as a `CharField` with a maximum length of 100 characters.
                # https://docs.djangoproject.com/en/5.0/ref/models/fields/#charfield

                ('review_text', models.TextField()),
                # *NOTES*
                # This line defines the `review_text` field as a `TextField` for storing large text.
                # https://docs.djangoproject.com/en/5.0/ref/models/fields/#textfield

                ('rating', models.IntegerField()),
                # *NOTES*
                # This line defines the `rating` field as an `IntegerField` for storing integer values.
                # https://docs.djangoproject.com/en/5.0/ref/models/fields/#integerfield
            ],
        ),
    ]
