# Generated by Django 3.1.5 on 2021-01-18 09:56
# *NOTES*
# This comment indicates that the file was automatically generated by Django during a migration.
# The migration was generated using Django version 3.1.5 on January 18, 2021 at 09:56.

import django.core.validators
# *NOTES*
# This line imports the `validators` module from `django.core`.
# The `validators` module contains various built-in validators that can be used to validate model fields.
# https://docs.djangoproject.com/en/5.0/ref/validators/

from django.db import migrations, models
# *NOTES*
# This line imports the `migrations` and `models` modules from `django.db`.
# `migrations` is used to create database schema migrations.
# `models` is used to define the database schema using Django models.
# https://docs.djangoproject.com/en/5.0/topics/migrations/
# https://docs.djangoproject.com/en/5.0/ref/models/

class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0001_initial'),
        # *NOTES*
        # This list specifies the dependencies for this migration.
        # This migration depends on the initial migration (`0001_initial`) of the `book_outlet` app.
        # https://docs.djangoproject.com/en/5.0/ref/migration-operations/#django.db.migrations.operations.Migration
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
            # *NOTES*
            # This operation adds a new field `author` to the `Book` model.
            # The `author` field is a character field with a maximum length of 100.
            # The `null=True` argument allows this field to be optional.
            # https://docs.djangoproject.com/en/5.0/ref/models/fields/#charfield
        ),
        migrations.AddField(
            model_name='book',
            name='is_bestselling',
            field=models.BooleanField(default=False),
            # *NOTES*
            # This operation adds a new field `is_bestselling` to the `Book` model.
            # The `is_bestselling` field is a boolean field.
            # The `default=False` argument sets the default value to `False`.
            # https://docs.djangoproject.com/en/5.0/ref/models/fields/#booleanfield
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            # *NOTES*
            # This operation alters the `rating` field of the `Book` model.
            # The `rating` field is an integer field with validators to ensure the rating is between 1 and 5.
            # `MinValueValidator` and `MaxValueValidator` are used to enforce the minimum and maximum values, respectively.
            # https://docs.djangoproject.com/en/5.0/ref/models/fields/#integerfield
            # https://docs.djangoproject.com/en/5.0/ref/validators/#minvaluevalidator
            # https://docs.djangoproject.com/en/5.0/ref/validators/#maxvaluevalidator
        ),
    ]
    # *NOTES*
    # The `operations` list contains the operations that will be applied to the database when this migration is run.
    # In this case, it contains three operations: adding the `author` and `is_bestselling` fields and altering the `rating` field in the `Book` model.
    # https://docs.djangoproject.com/en/5.0/ref/migration-operations/
