# Generated by Django 3.1.5 on 2021-01-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        # *NOTES*
        # This removes the `image_name` field from the `Post` model.
        # https://docs.djangoproject.com/en/5.0/ref/migrations/#django.db.migrations.operations.RemoveField

        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        # *NOTES*
        # This adds an `image` field to the `Post` model, which is an `ImageField` that uploads images to the 'posts' directory.
        # The field is nullable.
        # https://docs.djangoproject.com/en/5.0/ref/models/fields/#imagefield
    ]
