# Generated by Django 3.1.5 on 2021-01-27 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210127_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('user_email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=400)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
        ),
        # *NOTES*
        # This creates a new model named `Comment` with fields `id`, `user_name`, `user_email`, `text`, and `post`.
        # The `post` field is a foreign key to the `Post` model and is related by a one-to-many relationship.
        # https://docs.djangoproject.com/en/5.0/ref/models/fields/
    ]
