# Generated by Django 3.1.5 on 2021-01-18 09:32
# *NOTES*
# This comment indicates that the file was automatically generated by Django during a migration.
# The migration was generated using Django version 3.1.5 on January 18, 2021 at 09:32.

from django.db import migrations, models
# *NOTES*
# This line imports the `migrations` and `models` modules from `django.db`.
# `migrations` is used to create database schema migrations.
# `models` is used to define the database schema using Django models.
# https://docs.djangoproject.com/en/5.0/topics/migrations/
# https://docs.djangoproject.com/en/5.0/ref/models/

class Migration(migrations.Migration):

    initial = True
    # *NOTES*
    # This line indicates that this is the initial migration for the app.
    # The `initial` attribute is set to `True` for the first migration.

    dependencies = [
    ]
    # *NOTES*
    # This list specifies the dependencies for this migration.
    # Since this is the initial migration, there are no dependencies.
    # https://docs.djangoproject.com/en/5.0/ref/migration-operations/#django.db.migrations.operations.Migration

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # *NOTES*
                # This line defines an `id` field for the `Book` model.
                # The `id` field is an auto-incrementing primary key that is automatically created.
                # https://docs.djangoproject.com/en/5.0/ref/models/fields/#auto-field
                
                ('title', models.CharField(max_length=50)),
                # *NOTES*
                # This line defines a `title` field for the `Book` model, which is a character field with a maximum length of 50.
                # `CharField` is used for short to medium-length strings.
                # https://docs.djangoproject.com/en/5.0/ref/models/fields/#charfield

                ('rating', models.IntegerField()),
                # *NOTES*
                # This line defines a `rating` field for the `Book` model, which is an integer field.
                # `IntegerField` is used to store integer values.
                # https://docs.djangoproject.com/en/5.0/ref/models/fields/#integerfield
            ],
        ),
    ]
    # *NOTES*
    # The `operations` list contains the operations that will be applied to the database when this migration is run.
    # In this case, it contains a single operation to create the `Book` model with the specified fields.
    # https://docs.djangoproject.com/en/5.0/ref/migration-operations/#createmodel
