# Generated by Django 3.1.5 on 2021-01-18 14:00
# *NOTES*
# This comment indicates that the file was automatically generated by Django during a migration.
# The migration was generated using Django version 3.1.5 on January 18, 2021 at 14:00.

from django.db import migrations, models
# *NOTES*
# This line imports the `migrations` and `models` modules from `django.db`.
# `migrations` is used to create database schema migrations.
# `models` is used to define the database schema using Django models.
# https://docs.djangoproject.com/en/5.0/topics/migrations/
# https://docs.djangoproject.com/en/5.0/ref/models/

class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_auto_20210118_0956'),
        # *NOTES*
        # This list specifies the dependencies for this migration.
        # This migration depends on the second migration (`0002_auto_20210118_0956`) of the `book_outlet` app.
        # https://docs.djangoproject.com/en/5.0/ref/migration-operations/#django.db.migrations.operations.Migration
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=''),
            # *NOTES*
            # This operation adds a new field `slug` to the `Book` model.
            # The `slug` field is a slug field, which is used for storing URL-friendly representations of strings.
            # The `default=''` argument sets the default value of this field to an empty string.
            # https://docs.djangoproject.com/en/5.0/ref/models/fields/#slugfield
        ),
    ]
    # *NOTES*
    # The `operations` list contains the operations that will be applied to the database when this migration is run.
    # In this case, it contains a single operation to add the `slug` field to the `Book` model.
    # https://docs.djangoproject.com/en/5.0/ref/migration-operations/
