# Generated by Django 3.1.5 on 2021-01-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_auto_20210119_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book_outlet.author'),
        ),
        # *NOTES*
        # This operation modifies the `author` field in the `Book` model.
        # The `author` field is now a foreign key to the `Author` model.
        # The `null=True` argument allows this field to be optional.
        # The `on_delete=django.db.models.deletion.CASCADE` argument specifies that when the referenced `Author` object is deleted, the `Book` object should also be deleted.
        # The `related_name='books'` argument sets the name of the reverse relation from `Author` to `Book` to `books`.
        # https://docs.djangoproject.com/en/5.0/ref/models/fields/#foreignkey
        # https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.ForeignKey.on_delete
        # https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.ForeignKey.related_name
    ]
