# Generated by Django 3.1.5 on 2021-01-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_auto_20210119_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=80)),
                ('postal_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        # *NOTES*
        # This operation creates a new model called `Address`.
        # The `Address` model has four fields: `id`, `street`, `postal_code`, and `city`.
        # The `id` field is an automatically generated primary key.
        # The `street` field is a character field with a maximum length of 80.
        # The `postal_code` field is a character field with a maximum length of 5.
        # The `city` field is a character field with a maximum length of 50.
        # https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.AutoField
        # https://docs.djangoproject.com/en/5.0/ref/models/fields/#charfield

        migrations.AddField(
            model_name='author',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_outlet.address'),
        ),
        # *NOTES*
        # This operation adds an `address` field to the `Author` model.
        # The `address` field is a one-to-one relationship to the `Address` model.
        # The `null=True` argument allows this field to be optional.
        # The `on_delete=django.db.models.deletion.CASCADE` argument specifies that when the referenced `Address` object is deleted, the `Author` object should also be deleted.
        # https://docs.djangoproject.com/en/5.0/ref/models/fields/#onetoonefield
        # https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.OneToOneField.on_delete
    ]
